mod actor_like;
mod character_like;
mod describable;
mod equippable;
mod has_display_name;
mod has_placement;
mod has_skills;
mod has_stats;
mod identifiable;
mod item;
mod massive;
mod ownable;
mod spatial_query_engine;

pub use actor_like::ActorLike;
pub use character_like::CharacterLike;
pub use describable::Describable;
pub use equippable::Equippable;
pub use has_display_name::HasDisplayName;
pub use has_placement::HasPlacement;
pub use has_skills::HasSkills;
pub use has_stats::HasStats;
pub use identifiable::Identifiable;
pub use item::Item;
pub use massive::Massive;
pub use ownable::Ownable;
pub use spatial_query_engine::SpatialQueryEngine;
